### ISSUE TITLE
Whenever I try to run the lagdrop_ps4.sh script my router kills it.

### ISSUE THREAD

**Issue by robnelovera** [42Kmi/LagDrop#1]
I'd like to know why this is happening, It's so weird because I have enough flash memory, don't know if the killing has something to do with the ram memory on my device, I have a Linksys E2500 v1.

**Comment by 42Kmi** [comment]
Thanks for using LagDrop and thanks for contacting. Could you provide more details about your router killing the it? What version of DD-WRT are you running?

**Comment by 42Kmi** [comment]
Thanks for using LagDrop and thanks for contacting. Could you provide more details about your router killing LagDrop? What version of DD-WRT are you running?

**Comment by robnelovera** [comment]
Hello! Thanks for the fast answer, I'm running this DD-WRT version: v24-sp2 (12/15/14) vpn - build 25648, as I stated above my router is a Linksys E2500, I've tried to run the script from the DD-WRT command line and it shows "Killed" when I start it, also tried to run it from PuTTy and as I can see the live feed from the router it shows endless "Killed" until I close putty, for some reason I can't follow one of the steps in the guide, the part where I should chmod the files ticking the checkbox in properties, it's already set on 0755 though.

**Comment by 42Kmi** [comment]
Can you share screenshots of your DD-WRT web interface concerning your LagDrop setup? Specifically Administration > Cron section, and Services > Static Leases

**Comment by robnelovera** [comment]
Cron section: https://gyazo.com/812fdb99b482a377a97229543d0af8fd

Static leases: https://gyazo.com/f820dd760d8b0bc7f7fbdd69082666ef

I haven't added any instructions to the Cron section as I'm not able to proceed with the run lagdrop file step.

**Comment by 42Kmi** [comment]
Were the 42Kmi directory and the options_ps4.txt file created?

**Comment by robnelovera** [comment]
No, they weren't created :/

**Comment by 42Kmi** [comment]
Could you tell me which script you ran in putty? How?

**Comment by robnelovera** [comment]
Telnet to the router, command sh /jffs/lagdrop_ps4.sh, files are on the jffs folder but  seems like I can't run them... I have like 3 mb free on my flash memory so I have no clue about why the script is killed... Changed the DD-WRT version like three times, bounced between mini, VPN and BIG versions without luck, when I use WinSCP I use the SCP protocol to connect to the router, read somewhere that it might be the problem to change the permissions but so far I was able to change them individually on each lagdrop file... About to smash my head with this stuff as I want to test it.

**Comment by 42Kmi** [comment]
Forgot to ask, Are you running the current release of LagDrop or the beta?

Try using the lagdrop_wiiu.sh script. Change your PS4's static name for
from ps4 to wiiu and run it to see if that works. This will help determine
whether there's an issue with specific to the PS4 script or LagDrop in
general.

**Comment by robnelovera** [comment]
I'm using version 2.0.8. 

Same error when I tried with the wiiu.sh file: https://gyazo.com/318c04ff23a731c14a5ac2c45494b87e

**Comment by 42Kmi** [comment]
Try changing permissions to 777

**Comment by 42Kmi** [comment]
The last resort option is to manually create the 42Kmi directory and the options_ps4.txt file

In WinSCP, create a folder in the same directory as the LagDrop scripts named "42Kmi" without quotes and K must be capitalized.

Download this file (https://mega.nz/#!WtxEjJiY!InAcjPX0lIcNANZrLe3TldwesDwX50Dblzps_FrzsSY) and add it to the 42Kmi directory, or continue reading to create the file yourself.

In the 42Kmi folder, right-click to create a new file. Name it options_ps4.txt. Open the options_ps4.txt file.
Add the following inside the options_ps4.txt file and save:
ps4=192.168.1.143
PINGLIMIT=90
COUNT=5
SIZE=1024
MODE=1
MAXTTL=10
PROBES=5
TRACELIMIT=30
ACTION=REJECT
CHECKPACKETLOSS=OFF
PACKETLOSSLIMIT=80
SENTINEL=OFF
CLEARALLOWED=OFF
CLEARBLOCKED=OFF
CLEARLIMIT=10
CHECKPORTS=NO
PORTS=
RESTONMULTIPLAYER=NO
NUMBEROFPEERS=
SWITCH=ON
;

**Comment by robnelovera** [comment]
Ok, I followed all instructions, created everything successfully and went ahead to add the cron job into the router settings, how do I know if the script is running?

**Comment by 42Kmi** [comment]
You can run lagdropcount.sh in putty, which displays and updates counts of how many peers have been blocked/allowed every 5 seconds.

**Comment by 42Kmi** [comment]
You can run lagdropcount.sh in putty, which displays and updates counts of
how many peers have been blocked/allowed every 5 seconds.

**Comment by robnelovera** [comment]
Seems like PuTTy read the lagdropcount.sh script without any issue.

 I'm trying this thing with FIFA but so far it doesn't indicate whether it allows or block people, because I connected to several already and count is still showing solid zeros. Any idea?

**Comment by 42Kmi** [comment]
Send a pic of your cron

**Comment by 42Kmi** [comment]
If you want to test that LagDrop is indeed running, you can change the console IP in options_ps4.txt to your computer's IP address, save and browse the internet. You can use # to change values without having to delete them from the file, so:

ps4=192.168.1.143

would become

ps4=[PC's_IP_Address]#192.168.1.143

**Comment by robnelovera** [comment]
Cron: https://gyazo.com/521a20998eefa7fecf6b92a7560f0ed0

Gonna try that out and share if it works, thanks for all replies so far.

**Comment by robnelovera** [comment]
It's working with the IP of my PC guys, so I assume it must work with my PS4 aswell.

Thanks for helping me! Gonna figure out how to config. it with FIFA!

**Comment by 42Kmi** [comment]
If you can find EA server IPs, you can add them to /jffs/42Kmi/whitelist.txt so LagDrop does not check them
