### ISSUE TITLE
LagDrop running multiple instances

### ISSUE THREAD

**Issue by sidschingis** [42Kmi/LagDrop#7]
When I run LagDrop, it keeps spawning new instances and I'm not getting any peers to show up on the main console window even though people are connecting 
Any Ideas what the issue could be?

Router is an Archer c7 v5 running DD-WRT v3.0-r41586 std (11/21/19).
LagDrop is saved on an usb drive under /tmp/mnt/usb/LagDrop

**Comment by 42Kmi** [comment]
Join the 42Kmi discord and dm me
https://discord.gg/57jVKpU
